name: 'main.actor Documentation action'
description: 'Generates documentation for the release and uploads to main.actor'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  library_name:
    description: 'Name of the library being uploaded'
    required: true
  docs_build_dir:
    description: 'Location, relative to the Makefile, that generated documentation will be placed'
    required: true
  git_user_name:
    description: 'Name to associate with documentation commits'
    required: true
  git_user_email:
    description: 'Email to associate with documentation commits'
    required: true
